feat: added debug mode

diff --git a/bin/wofl b/bin/wofl
--- a/bin/wofl
+++ b/bin/wofl
@@ -13,10 +13,13 @@ Example w/ Typescript template:
     wofl new <proj_name> -t typescript
 "
 
+
+
 # Created by argbash-init v2.8.1
 # ARG_POSITIONAL_SINGLE([command],[Command.  Currently only supports 'new'],[])
 # ARG_POSITIONAL_SINGLE([directory],[Directory name of new project.],[])
 # ARG_OPTIONAL_SINGLE([template],[t],[A option with short and long flags and default],[base])
+# ARG_OPTIONAL_BOOLEAN([debug],[d],[Debug mode])
 # ARG_DEFAULTS_POS()
 # ARG_HELP([Create a project based off of nix and git hooks workflow.],[$help_msg])
 # ARG_VERSION([echo $0 v0.1])
@@ -40,7 +43,7 @@ die()
 
 begins_with_short_option()
 {
-  local first_option all_short_options='thv'
+  local first_option all_short_options='tdhv'
   first_option="${1:0:1}"
   test "$all_short_options" = "${all_short_options/$first_option/}" && return 1 || return 0
 }
@@ -51,15 +54,17 @@ _arg_command=
 _arg_directory=
 # THE DEFAULTS INITIALIZATION - OPTIONALS
 _arg_template="base"
+_arg_debug="off"
 
 
 print_help()
 {
   printf '%s\n' "Create a project based off of nix and git hooks workflow."
-  printf 'Usage: %s [-t|--template <arg>] [-h|--help] [-v|--version] <command> <directory>\n' "$0"
+  printf 'Usage: %s [-t|--template <arg>] [-d|--(no-)debug] [-h|--help] [-v|--version] <command> <directory>\n' "$0"
   printf '\t%s\n' "<command>: Command.  Currently only supports 'new'"
   printf '\t%s\n' "<directory>: Directory name of new project."
   printf '\t%s\n' "-t, --template: A option with short and long flags and default (default: 'base')"
+  printf '\t%s\n' "-d, --debug, --no-debug: Debug mode (off by default)"
   printf '\t%s\n' "-h, --help: Prints help"
   printf '\t%s\n' "-v, --version: Prints version"
   printf '\n%s\n' "$help_msg"
@@ -83,6 +88,18 @@ parse_commandline()
         ;;
       -t*)
         _arg_template="${_key##-t}"
+        ;;
+      -d|--no-debug|--debug)
+        _arg_debug="on"
+        test "${1:0:5}" = "--no-" && _arg_debug="off"
+        ;;
+      -d*)
+        _arg_debug="on"
+        _next="${_key##-d}"
+        if test -n "$_next" -a "$_next" != "$_key"
+        then
+          { begins_with_short_option "$_next" && shift && set -- "-d" "-${_next}" "$@"; } || die "The short option '$_key' can't be decomposed to ${_key:0:2} and -${_key:2}, because ${_key:0:2} doesn't accept value and '-${_key:2:1}' doesn't correspond to a short option."
+        fi
         ;;
       -h|--help)
         print_help
@@ -143,55 +160,54 @@ assign_positional_args 1 "${_positionals[@]}"
 # [ <-- needed because of Argbash
 
 
-# exit on errors
-set -e
 
+## Exit on errors
+set -e
 function cleanup () {
   rm -rf $_arg_directory
 }
-
 trap cleanup ERR
 
 
 # Path helper variables
-bin_path="$(dirname $(readlink $0))"  # get path of `wofl` script
+bin_path="$(dirname $0)"
 root_path="$(dirname $bin_path)"
 templates_path="$root_path/templates"
 
-echo $bin_path
-echo $root_path
-echo $templates_path
+
+if [ $_arg_debug = 'on' ]; then
+  echo '[debug]: 0 = $0'
+  echo '[debug]: bin_path = $bin_path'
+  echo '[debug]: root_path = $root_path'
+  echo '[debug]: templates_path = $templates_path'
+fi
 
 # Main logic
-#
-#if [ "$_arg_command" != "new" ]; then
-#  echo "Only 'new' command is supported"
-#else
-#  if [ -z "$_arg_directory" ]; then
-#    echo "Must supply a directory name"
-#  fi
-#
-#  mkdir -p $_arg_directory
-#  rsync -r "$templates_path/$_arg_template/" "./$_arg_directory/"
-#
-#  # TODO change these to debug logs
-#  echo "Created folder '$_arg_directory' with template '$_arg_template'"
-#
-#  echo "Navigating into '$_arg_directory'..."
-#  cd $_arg_directory
-#
-#  # Manually drop into nix shell if `direnv` is not installed.
-#  if [ -z "$(command -v direnv)" ]; then
-#    nix-shell
-#  fi
-#
-#  echo "Initializing git repo..."
-#  git init
-#
-#  echo "Installing git hooks..."
-#  lefthook install
-#
-#  echo "Done"
-#fi
-#
+
+if [ "$_arg_command" != "new" ]; then
+  echo "Only 'new' command is supported"
+else
+  if [ -z "$_arg_directory" ]; then
+    echo "Must supply a directory name"
+  fi
+
+  mkdir -p $_arg_directory
+  rsync -r "$templates_path/$_arg_template/" "./$_arg_directory/"
+
+  # TODO change these to debug logs
+  echo "Created folder '$_arg_directory' with template '$_arg_template'"
+
+  echo "Navigating into '$_arg_directory'..."
+  cd $_arg_directory
+
+  echo "Initializing git repo..."
+  git init
+
+  # Setup git hooks
+  echo "Setting up git hooks..."
+  nix-shell --run 'lefthook install'
+
+  echo "Done"
+fi
+
 # ] <-- needed because of Argbash
